services:
    _defaults:
        autowire: true
        autoconfigure: true

    Mandrael\ContaoBackendIconVisibilityBundle\:
        resource: '../src/'
        exclude:
            - '../src/MandraelContaoBackendIconVisibilityBundle.php'
            - '../src/ContaoManager/'
            - '../src/DataContainer/'
            - '../src/DependencyInjection/'
